"""Update Book model with file upload and description

Revision ID: 1cd982c8bd75
Revises: 3556458810c0
Create Date: 2024-11-25 14:47:02.846197

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cd982c8bd75'
down_revision = '3556458810c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('file_path', sa.String(length=255), nullable=False))
        batch_op.drop_index('isbn')
        batch_op.drop_column('isbn')
        batch_op.drop_column('copies_available')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('copies_available', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('isbn', mysql.VARCHAR(length=13), nullable=True))
        batch_op.create_index('isbn', ['isbn'], unique=True)
        batch_op.drop_column('file_path')
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
